### ISSUE TITLE
Storybook not working 

### ISSUE THREAD

**Issue by fhconte** [konsalex/design-system-newline-course#1]
```
info @storybook/react v6.5.10
info
info => Loading presets
info Addon-docs: using MDX1
info => Using implicit CSS loaders
(node:8892) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Using default Webpack4 setup
10% building 1/1 modules 0 active
info => Ignoring cached manager due to change in manager config
10% building 1/13 modules 12 active C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack-hot-middleware\client.js?reload=true&quiet=false&noInfo=undefinednode:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\thegr\Downloads\design-system-newline-course\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\thegr\Downloads\design-system-newline-course\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\thegr\Downloads\design-system-newline-course\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at C:\Users\thegr\Downloads\design-system-newline-course\node_modules\loader-runner\lib\LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Node.js v20.11.0

**Comment by konsalex** [comment]
@fhconte can you try Node v16? The Storybook course is with Storybook v6 so there might be an issue there 🤔 If not I can help you debug

**Comment by fhconte** [comment]
Worked perfectly with Node 16. 
You can set engines node = 16 on package.json like below :)

```
{
  "engines": {
    "node": "=16"
  }
}
```

**Comment by fhconte** [comment]
Additionally I will build the same structure using Storybook 8 inside the docs pkg with the course.

I think its the only issue about using Node 20 inside this repo. Thank you!
